### ISSUE TITLE
[Bug] Exception when using Qdrant v1.8.0

### ISSUE THREAD

**Issue by marcominerva** [microsoft/kernel-memory#347]
### Context / Scenario

Using Qdrant to v1.8.0, saving embeddings results in an exception.

### What happened?

Using Qdrant to v1.8.0 (a fresh installation, so no collection at all), when trying to save embeddings, some are actually inserted in the database, then I get this exception:

```
dbug: Microsoft.KernelMemory.Handlers.SaveRecordsHandler[0]
      Saving memory records, pipeline 'default/c3ef6467901547f192545192d1a08154202403070405183320012'
fail: Microsoft.KernelMemory.MemoryDb.Qdrant.Client.QdrantClient[0]
      CreateCollectionAsync failed: Response status code does not indicate success: 409 (Conflict)., {"status":{"error":"Wrong input: Collection `default` already exists!"},"time":0.000117352}
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (Conflict).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.KernelMemory.MemoryDb.Qdrant.Client.QdrantClient`1.ValidateResponse(HttpResponseMessage response, String content, String methodName)
warn: Microsoft.KernelMemory.Pipeline.Queue.DevTools.SimpleQueues[0]
      Message '20240307.160525.8372403.38151cc62a4f40188c677cdbb72326e1' processing failed with exception, putting message back in the queue. Message content: {"index":"default","document_id":"c3ef6467901547f192545192d1a08154202403070405183320012","execution_id":"72dd3acd27c041eca8c57a3fed74f27a","steps":["extract","partition","gen_embeddings","save_records"]}
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (Conflict).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.KernelMemory.MemoryDb.Qdrant.Client.QdrantClient`1.ValidateResponse(HttpResponseMessage response, String content, String methodName)
         at Microsoft.KernelMemory.MemoryDb.Qdrant.Client.QdrantClient`1.CreateCollectionAsync(String collectionName, Int32 vectorSize, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.SaveEmbeddingsAsync(DataPipeline pipeline, CancellationToken cancellationToken)
```

Reverting Qdrant to v1.7.4, everything works as excepted.

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

Kernel Memory v0.32.240307.2 (I have tried also with v0.30.240227.1)

**Comment by marcominerva** [comment]
@dluc I have found the issue. In this code:

https://github.com/microsoft/kernel-memory/blob/61fb2b5789ba51543ab947a604dc8c1db3ac8bf1/extensions/Qdrant/Qdrant/Client/QdrantClient.cs#L91-L102

At lines 98 there is a check for `BadRequest` response. Starting with Qdrant v1.8.0 (and the newest 1.8.1), this API returns **409 Conflict** instead of **400 Bad Request**.

I have create a PR to fix this issue: https://github.com/microsoft/kernel-memory/pull/348

**Comment by dluc** [comment]
Fixed in Microsoft.KernelMemory.Core 0.32.240308.1

**Comment by mplogas** [comment]
Hi everyone, 
I applied the patch suggested by Marco but the issue remains. 

Environment:
dotnet: 8.0.1
Qdrant v1.8.0 and v1.8.1

Repro: 
1. setup queue & qdrant (or, purge queue and drop 'default' collection)
2. clone repro & apply the patch
3. configure appsettings.Development.json to use Rabbit (or SimpleQueues), Qdrant and AOAI
4. run service using Kestrel (or Docker, doesn't matter)
5. POST a file to <ip>:9001/update
6. error message
```
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Queueing upload of 1 files for further processing [request 20240308.170507.0a3800f3f10a4de3825411df992cef12]
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      File uploaded: IoT Enabled Coffee Machine via ESPHome.md, 2829 bytes
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Handler 'extract' processed pipeline 'default/20240308.170507.0a3800f3f10a4de3825411df992cef12' successfully
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Handler 'partition' processed pipeline 'default/20240308.170507.0a3800f3f10a4de3825411df992cef12' successfully
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Handler 'gen_embeddings' processed pipeline 'default/20240308.170507.0a3800f3f10a4de3825411df992cef12' successfully
fail: Microsoft.KernelMemory.MemoryDb.Qdrant.Client.QdrantClient[0]
      CreateCollectionAsync failed: Response status code does not indicate success: 409 (Conflict)., {"status":{"error":"Wrong input: Collection `default` already exists!"},"time":0.000033282}
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (Conflict).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.KernelMemory.MemoryDb.Qdrant.Client.QdrantClient`1.ValidateResponse(HttpResponseMessage response, String content, String methodName)
fail: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Pipeline start failed
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (Conflict).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.KernelMemory.MemoryDb.Qdrant.Client.QdrantClient`1.ValidateResponse(HttpResponseMessage response, String content, String methodName)
         at Microsoft.KernelMemory.MemoryDb.Qdrant.Client.QdrantClient`1.CreateCollectionAsync(String collectionName, Int32 vectorSize, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.SaveEmbeddingsAsync(DataPipeline pipeline, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.InvokeAsync(DataPipeline pipeline, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator.RunPipelineAsync(DataPipeline pipeline, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Pipeline.BaseOrchestrator.ImportDocumentAsync(String index, DocumentUploadRequest uploadRequest, CancellationToken cancellationToken)
```

**Comment by marcominerva** [comment]
I have just tried cloning the repro (`main` branch), everything works as expected using Qdrant v1.8.1

**Comment by dluc** [comment]
Tested both serverless and async service with Qdrant 1.7.4, 1.8.0, 1.8.1. All tests are passing, 409 is handled as expected.
